### ISSUE TITLE
APK release on GitHub and F-Droid 

### ISSUE THREAD

**Issue by baimafeima** [proxysh/Safejumper-for-Android#1]
I am quite excited about your software but have been unable to find it on F-Droid. Is it possible to have it added to their repository, as well as offer an APK file here on GitHub to allow for manual installation? Many thanks.

**Comment by proxysh** [comment]
You can download the latest APK at https://proxy.sh/safejumper.apk, the URL will stay the same. We usually do not publish APK outside Google Play; and we do not publish it here because it's a Proxy.sh-tight APK, while the project here is ought to be more universal.

**Comment by baimafeima** [comment]
How can I validate the .apk package? I just realized that proxy.sh would not meet the requirements of F-Droid due to its commercial nature. In that case, I think a clearly visible and downloadable .apk file on your website is probably the best option.

**Comment by threemonkeys** [comment]
It is not visible because we distribute it via Google Play, but it is always there under https://proxy.sh/safejumper.apk

**Comment by proxysh** [comment]
It is not visible because we distribute it via Google Play, but it is always there under https://proxy.sh/safejumper.apk
