### ISSUE TITLE
Build Failed.

### ISSUE THREAD

**Issue by rafiip** [proxysh/Safejumper-for-Android#8]
Hi . 
project does not build properly. it gives the following error:
Build Failed. ProcessException: Error configuring
and in the details it says :
Execution failed for task ':app:generateJsonModelNoovpn3Debug'.

**Comment by proxysh** [comment]
Have you tried the Safejumper Plus code?
 
You should add the right dependency for it. Sadly, we do not provide support for rebuilding Safejumper.
